### ISSUE TITLE
Implement Changes from Code Review

### ISSUE THREAD

**Issue by MuckT** [crypto-tracks/crypto-tracker-frontend#16]
### Descriptions
Implement code changes #11

### Tasks
- [ ] Implement code changes.
- [ ] Update tests
- [ ] Deploy changes to dev.
- [ ] Deploy changes to prod.
